name: Release new version

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Set up git credentials
        run: |
          git config --global user.name 'ci'
          git config --global user.email 'deploy@monday.com'

      - name: Set package version variable
        run: echo "package_version=$(node -e "console.log(require('./package.json').version)")" >> "$GITHUB_ENV"

      - name: Commit and push changes if version updated
        run: |
          VERSION_UPDATED=$(git status --porcelain | grep package.json | wc -l)
          if [ "$VERSION_UPDATED" -eq "1" ]; then
            git add package.json
            git commit -m "chore(release): ${{ env.package_version }}"
            git tag -a "v${{ env.package_version }}" -m "Release version ${{ env.package_version }}"
            git push --follow-tags
          else
            echo "Version not updated in package.json, skipping commit and tag."
          fi

      - name: Publish the new version to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TEST_VIBE }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TEST_PAT_OF_USER_SM }}"
          prerelease: false
          automatic_release_tag: "v${{ env.package_version }}"
