name: Release new version

on:
  push:
    branches:
      - production

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          registry-url: https://registry.npmjs.org/
      
      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: npm ci

      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Build packages with Lerna
        run: npx lerna run build

      - name: Publish the new version to npm
        run: npx lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_IKI_VIBE }}